# AndroidX is required by Google Mobile Ads SDK
android.useAndroidX=true
android.enableJetifier=true

# Gradle / JVM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Build performance
org.gradle.parallel=true
org.gradle.caching=true

signingConfigs {
    release {
        storeFile file(System.getenv("ANDROID_KEYSTORE_PATH"))
        storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
        keyAlias System.getenv("ANDROID_KEY_ALIAS")
        keyPassword System.getenv("ANDROID_KEY_PASSWORD")
    }
}

buildTypes {
    release {
        minifyEnabled false
        signingConfig signingConfigs.release
    }
}

defaultConfig {
    applicationId "ir.keynu.hormuzmines"
}