plugins { id 'com.android.application' }

android {
    namespace 'ir.keynu.taptile'
    compileSdk 35
    defaultConfig {
        applicationId 'ir.keynu.taptile'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '2.0.7'
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {}
